print("----Millenium Eye----")
print("Developed By NamesJoeyWheeler")
print("")
var = input("Enter Stan Episode/Movie ID: ")
print("---------------------------------")
print("https://v12.cat.api.stan.com.au/programs/" + str(var))
print(".json")
