print("----Millenium Eye----")
print("Developed By NamesJoeyWheeler")
print("")
var = input("Enter Stan Episode/Movie ID: ")
print("---------------------------------")
print("https://api.stan.com.au/cat/v12/programs/" + str(var) + ".json")
