print("----Millenium Eye----")
print("----Sub Extractor----")
print("Developed By NamesJoeyWheeler")
print("")
var = input("Enter Stan Episode/Movie ID: ")
print("---------------------------------")
print("https://streamcott-a.akamaihd.net/" + str(var))
print("A-1/eng.vtt")
print("---------------------------------")
var = input("Link Not Working? Enter The ID Again To Get A New Link: ")
print("---------------------------------")
print("https://streamcott-a.akamaihd.net/" + str(var))
print("B-1/eng.vtt")
var = input("Link Not Working? Enter The ID Again To Get A New Link: ")
print("---------------------------------")
print("https://streamcott-a.akamaihd.net/" + str(var))
print("C-1/eng.vtt")
var = input("Link Not Working? Enter The ID Again To Get A New Link: ")
print("---------------------------------")
print("https://streamcott-a.akamaihd.net/" + str(var))
print("D-1/eng.vtt")
print("---------------------------------")
print("Still not working? Please go to the GitHub page and report this problem with the link you want to get")

